In [264]:
import numpy as np

In [265]:
arr1 = np.arange(1, 11, 1)
print(arr1)

[ 1  2  3  4  5  6  7  8  9 10]


In [266]:
arr2 = np.arange(1, 21, 2)
print(arr2)

[ 1  3  5  7  9 11 13 15 17 19]


In [267]:
print(arr1 + arr2)
print(arr1 - arr2)
print(arr1 * arr2)
print(arr1 / arr2)

[ 2  5  8 11 14 17 20 23 26 29]
[ 0 -1 -2 -3 -4 -5 -6 -7 -8 -9]
[  1   6  15  28  45  66  91 120 153 190]
[1.         0.66666667 0.6        0.57142857 0.55555556 0.54545455
 0.53846154 0.53333333 0.52941176 0.52631579]


In [268]:
print(arr1[0:3])

[1 2 3]


In [269]:
arr3 = np.array([1, 2, 3, 4, 5, 6])
np.reshape(arr3, (-1, 3))

array([[1, 2, 3],
       [4, 5, 6]])

In [270]:
print(arr1.mean())
print(np.median(arr1))
print(arr1.std())

5.5
5.5
2.8722813232690143


In [271]:
import pandas as pd

In [272]:
data = {'Name': ['Max', 'Sam', 'Josh', 'Richard', 'Thomas', 'Ben'],
 'Age': [34, 20, 41, 45, 67, 19], 'Weight': [145, 111, 165, 143, 156, 132]}
df1 = pd.DataFrame(data)
print(df1)

      Name  Age  Weight
0      Max   34     145
1      Sam   20     111
2     Josh   41     165
3  Richard   45     143
4   Thomas   67     156
5      Ben   19     132


In [273]:
df1['City'] = ['New York', 'Los Angeles', 'Boston', 'Boston', 'Boston', 'New York']
df1['Weight-Age'] = df1['Weight'] - df1['Age']
print(df1)

      Name  Age  Weight         City  Weight-Age
0      Max   34     145     New York         111
1      Sam   20     111  Los Angeles          91
2     Josh   41     165       Boston         124
3  Richard   45     143       Boston          98
4   Thomas   67     156       Boston          89
5      Ben   19     132     New York         113


In [274]:
#Create condition
condition = df1['Age'] > 30
selected_rows = df1[condition]

print("\nRows where Age > 30:")
print(selected_rows)

#Select columns by title
selected_columns = df1[['Name', 'City']]

print("\nSelected columns ('Name' and 'City'):")
print(selected_columns)


Rows where Age > 30:
      Name  Age  Weight      City  Weight-Age
0      Max   34     145  New York         111
2     Josh   41     165    Boston         124
3  Richard   45     143    Boston          98
4   Thomas   67     156    Boston          89

Selected columns ('Name' and 'City'):
      Name         City
0      Max     New York
1      Sam  Los Angeles
2     Josh       Boston
3  Richard       Boston
4   Thomas       Boston
5      Ben     New York


In [275]:
grouped_df = df1.groupby('City')

#Calculate the mean of each group, excluding non-numeric columns
mean_df = grouped_df.mean(numeric_only=True)

#Display the mean of each group
print("\nMean of each group:")
print(mean_df)


Mean of each group:
              Age      Weight  Weight-Age
City                                     
Boston       51.0  154.666667  103.666667
Los Angeles  20.0  111.000000   91.000000
New York     26.5  138.500000  112.000000


In [276]:
df1['Age'].replace(34, np.nan, inplace=True)
print(df1)

      Name   Age  Weight         City  Weight-Age
0      Max   NaN     145     New York         111
1      Sam  20.0     111  Los Angeles          91
2     Josh  41.0     165       Boston         124
3  Richard  45.0     143       Boston          98
4   Thomas  67.0     156       Boston          89
5      Ben  19.0     132     New York         113


In [277]:
df_dropped = df1.dropna()
print("\nDataFrame after Removing Rows with Missing Values:")
print(df_dropped)


DataFrame after Removing Rows with Missing Values:
      Name   Age  Weight         City  Weight-Age
1      Sam  20.0     111  Los Angeles          91
2     Josh  41.0     165       Boston         124
3  Richard  45.0     143       Boston          98
4   Thomas  67.0     156       Boston          89
5      Ben  19.0     132     New York         113
