In [1]:
import numpy as np

In [2]:
arr1 = np.array([1, 2, 3, 4, 5])

arr2 = np.zeros(5)

arr3 = np.ones((3,3))

arr4 = np.arange(2, 10, 2)

arr5 = np.random.random((3, 3))

print(arr1, arr2, arr3, arr4, arr5)

#accessing elements
print(arr1[0])

#slicing
print(arr1[1:4])

[1 2 3 4 5] [0. 0. 0. 0. 0.] [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]] [2 4 6 8] [[0.57806266 0.42519754 0.7362514 ]
 [0.77260453 0.25338466 0.75674221]
 [0.67010438 0.55834191 0.79530051]]
1
[2 3 4]


In [3]:
arr6 = arr1 + arr2
print(arr6)

[1. 2. 3. 4. 5.]


In [4]:
print(np.sum(arr1))

arr7 = arr1 * 2
print(arr7)

15
[ 2  4  6  8 10]


In [5]:
arr8 = np.arange(9).reshape(3, 3)
print(arr8)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [6]:
arr13 = np.sin(arr1)
print(arr13)

[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]


In [7]:
indices = np.array([0, 2, 4])
print(arr1[indices])

[1 3 5]


In [8]:
bool_arr = arr1 > 3
print(bool_arr)
print(arr1[bool_arr])

[False False False  True  True]
[4 5]


In [9]:
arr14 = arr1 + 10
print(arr14)

[11 12 13 14 15]


In [10]:
arr15 = arr1 + np.array([[10], [20], [30], [40], [50]])
print(arr15)

[[11 12 13 14 15]
 [21 22 23 24 25]
 [31 32 33 34 35]
 [41 42 43 44 45]
 [51 52 53 54 55]]
